### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by cristianmtr** [wayne391/Lead-Sheet-Analysis#2]
```
$ python main.py
[*] Scanning...
cpu count: 3, batch size: 7, total: 20
ps - 0 [from 0 to 7]
ps - 1 [from 7 to 14]
ps - 2 [from 14 to 20]
Process Process-3:
Traceback (most recent call last):
  File "D:\bin\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\bin\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\materiale\datasets\Lead-Sheet-Analysis-master\lead_sheet_dataset\src\main.py", line 58, in proc
    url = 'https://www.hooktheory.com/theorytab/view/' + tmp[-2] + '/' + tmp[-1]
IndexError: list index out of range
Process Process-2:
Traceback (most recent call last):
  File "D:\bin\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\bin\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\materiale\datasets\Lead-Sheet-Analysis-master\lead_sheet_dataset\src\main.py", line 58, in proc
    url = 'https://www.hooktheory.com/theorytab/view/' + tmp[-2] + '/' + tmp[-1]
IndexError: list index out of range
Process Process-1:
Traceback (most recent call last):
  File "D:\bin\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\bin\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\materiale\datasets\Lead-Sheet-Analysis-master\lead_sheet_dataset\src\main.py", line 58, in proc
    url = 'https://www.hooktheory.com/theorytab/view/' + tmp[-2] + '/' + tmp[-1]
IndexError: list index out of range
```

Any ideas?

**Comment by wayne391** [comment]
Hello, in line 57, I split the path by '/' .  But I found your path separator is '\\'. I run my codes on Ubuntu and I guess your environment is Windows. Maybe this causes the issue.
